### ISSUE TITLE
Handle validation errors for profile page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#152]
For example, if the wrong code is entered to confirm the email attestation, it will fail with only a console error. Let's not forget to surface these to the user.

- [x] Phone
- [x] Email
- [x] Facebook
- [x] Twitter
- [x] Airbnb

**Comment by gaboesquivel** [comment]
I can help with this one.  I Just [stumbled upon it](https://monosnap.com/file/kcfQ4E8nqcBeYINkBSOtW073ESa55t) trying to validate twitter, some sort of (at least basic) UI feedback is definitively required.

**Comment by micahalcorn** [comment]
@gaboesquivel I'm in the middle of making some changes to that component flow right now. I'll let you know when I get my commits merged. 👍

**Comment by micahalcorn** [comment]
Done via #303 ✅
