### ISSUE TITLE
Enforce code formatting

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#166]
Add [Prettier](https://github.com/prettier/prettier) to enforce code formatting.

**Comment by gaboesquivel** [comment]
I like this type devops-ish / code quality / standards task.
 
This is related to IMO:
- Use StandardJS  https://github.com/OriginProtocol/origin-js/issues/166
- Use Error First and No Else Return to avoid deep nesting in JavaScript https://github.com/OriginProtocol/origin-js/issues/193
- Async JS Guidelines https://github.com/OriginProtocol/origin-js/issues/180 
- Let's use const https://github.com/OriginProtocol/origin-js/issues/192

I can add a pre-commit hook using husky to trigger prettier and ensure the right formatting.

**Comment by micahalcorn** [comment]
@tyleryasaka [it sounds like you might be taking this on](https://github.com/OriginProtocol/origin-js/pull/225#issuecomment-394588589).

**Comment by micahalcorn** [comment]
Done via #335 ✅
