### ISSUE TITLE
Existing progress bar does not start with correct state

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#208]
There seems to be a minor issue where the existing profile progress bar does not fill on route changes although it does fill on browser refreshes. The colored progress bar width should always match the strength number (40% in this example).

![profile-progress](https://user-images.githubusercontent.com/273937/40437169-3de0de72-5e7a-11e8-9782-5e43cc3fe8c1.gif)

**Comment by newdawn1989** [comment]
@micahalcorn I'd like to help with this one!

**Comment by micahalcorn** [comment]
Great, @newdawn1989 😄 Have you joined [our Discord](https://discordapp.com/invite/jyxpUSe) yet? Find me there in #engineering.

**Comment by newdawn1989** [comment]
I have not! Thank you for the invite! Downloading discord now!

**Comment by anshumanv** [comment]
Looking this up.

**Comment by micahalcorn** [comment]
Thanks @anshumanv 😄Please also consider changing your membership in the GitHub organization to public instead of private. https://help.github.com/articles/publicizing-or-hiding-organization-membership/

**Comment by anshumanv** [comment]
Ah forgot to do it, done @micahalcorn :+1: :100:

**Comment by anshumanv** [comment]
Hey @micahalcorn @davecraige will it be fine if the gitcoin guys fund this issue? :sparkles: :smile:

**Comment by davecraige** [comment]
Not sure how that will work to be honest.  

*dropped @vs77bb a note about this in the Gitcoin Slack.
