### ISSUE TITLE
[profile] page refresh required to update content in menu dropdown

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-dapp#223]
When the profile is updated (attestations or name), a page refresh is required to update the content in the menu dropdown

![screenshot 2018-05-26 00 13 42](https://user-images.githubusercontent.com/156263/40573695-e6564398-6079-11e8-96b7-acf6c2dd6031.png)

**Comment by dhruvkumar001** [comment]
I am working on this issue.

**Comment by dhruvkumar001** [comment]
Hi @ambertch,

The page should be refresh on Publish the profile or when user click on Continue button inside the popup?

**Comment by micahalcorn** [comment]
@dhruvkumar001 a refresh should not be required at all. The user dropdown should reactively update to show the new attestations or profile attributes.

**Comment by dhruvkumar001** [comment]
Okay will make it the way.

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin-dapp/pull/561 ✅
