### ISSUE TITLE
Price approximation failure

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#228]
@inkredabull @DanielVF 👇 

On a seemingly random basis, I get listing cards with USD prices sticking at "Loading..." due to the following (in Safari):

`[Error] Cross-origin redirection to https://api.cryptonator.com/api/ticker/eth-usd denied by Cross-Origin Resource Sharing policy: Access-Control-Allow-Origin cannot contain more than one origin.`

I tried reaching out to Cryptonator to see if we could whitelist the (Origin) origin, but I'm not getting anywhere. Do we want to just hide the price approximation until it loads successfully or is there a better fallback?

_This happens in Chrome also and in various environments._

**Comment by DanielVF** [comment]
We're currently hitting the API once for every listing - we might be tripping some kind of rate limiting. We can reuse the same conversion rate for multiple listings.

**Comment by wanderingstan** [comment]
@DanielVF good point. We should definitely hit the API once and store it for dapp-wide useage.

**Comment by inkredabull** [comment]
Wrapping up other responsibilities today before heading out on vacation tomorrow for a week. 
Have unassigned myself if it needs to get done sooner than the week of 6/18.

**Comment by inkredabull** [comment]
https://github.com/OriginProtocol/origin-dapp/pull/290

**Comment by micahalcorn** [comment]
Done via #290 ✅
