### ISSUE TITLE
Localize <Timelapse> component

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/origin-dapp#248]
Sub-task of: https://github.com/OriginProtocol/demo-dapp/pull/238

The `<Timelapse>` component is used to say how long ago an event occurred. 

It is currently english-only and needs to be internationalized. 

One possible strategy may be to use `moment-locale` in addition to or instead of the standard `moment` library, but more research is required.

**Comment by micahalcorn** [comment]
No longer necessary thanks to https://github.com/OriginProtocol/origin-dapp/pull/271 🎉
