### ISSUE TITLE
Localization - Integrate with Crowdin

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/origin-dapp#263]
As a developer, I want an easy (automated if possible) way to push source strings to Crowdin and pull translated files into the DApp.

The Crowdin GitHub integration seems like the most efficient workflow for integration with them:
https://support.crowdin.com/github-integration/

After creating a [configuration file](https://support.crowdin.com/configuration-file/) and configuring some stuff on the Crowdin dashboard, any branch that has an update to the translation files will be pulled into Crowdin for translation immediately. 

Each time a translator completes a translation, Crowdin generates a PR to the DApp repo with the updated strings in the appropriate JSON file. 

For file uploads, Crowdin accepts JSON files with this structure:
```
{
    "Key1": "",
    "Key2": "Source string 2",
    "Key3": "Source string 3"
}
```
So, our current script that converts the `react-intl` JSON to a .po file is unnecessary. We should be able to save a step in the workflow by keeping everything in JSON and writing a new script that pulls all of the `react-intl` JSON files together so that Crowdin can automatically pull it in via their GitHub integration. 

Tasks:
1. Come up with a dev workflow to make this as easy as possible for developers, translators, and proof-readers
2. Write scripts to automate the process as much as possible
3. Update translation documentation to describe the process

**Comment by wanderingstan** [comment]
I'm gonna say this is done. :)
