### ISSUE TITLE
Add new social links to footer and mimic company website

### ISSUE THREAD

**Issue by mek32390** [OriginProtocol/origin-dapp#279]
There is a PR open on the company website that includes new social links. We need it on the DApp as well.

**Comment by mek32390** [comment]
@matthewliu I made this issue after updating the company website footer. However, does it make sense for the DApp and the company website to have the same footer (like they currently do)? The company website is for marketing/business purposes, whereas the DApp is an application. Maybe a more simple footer with the copyright info would be more appropriate?

**Comment by micahalcorn** [comment]
Done via https://github.com/OriginProtocol/origin-dapp/pull/298 ✅
