### ISSUE TITLE
Appropriately Handle International Phone Numbers

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#286]
The bridge server uses Twilio for phone attestations. We currently tell the user that [we will send a verification code](https://github.com/OriginProtocol/origin-dapp/blob/7f3bba0f358154172af79abe2213cd42caa8a16b/src/pages/profile/VerifyPhone.js#L76). Depending on the country where the phone number is located, Twilio may be capable of sending an SMS message, make a phone call, or do neither. The bridge server appears to currently only [attempt to send an SMS message and otherwise raise an exception](https://github.com/OriginProtocol/origin-bridge/blob/b55a98dd3639677ac91537f34e9d3888bd087381/logic/attestation_service.py#L76-L82). This should be accounted for and the UI should surface an appropriate message.

See https://support.twilio.com/hc/en-us/articles/223183068-Twilio-international-phone-number-availability-and-their-capabilities 😕

**Comment by tomlinton** [comment]
Done by PR #301
