### ISSUE TITLE
Handle Uncaught Attestation Exceptions

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#287]
For example, if someone tries to verify a phone number for which Twilio cannot send SMS messages, an exception will be raised:

![screen shot 2018-06-23 at 10 20 21 pm](https://user-images.githubusercontent.com/273937/41816208-e91a5102-7733-11e8-8569-a8670d476737.jpg)

The DApp should render an alert instead of swallowing exceptions like this for each of the attestation services.

**Steps to Reproduce**

- Try to verify phone number 🇮🇹050835011
- Check the console

**Comment by tomlinton** [comment]
@sparrowDom I just saw in one of your recent commits that you've added supported for handling general errors like this (at least to the phone verification). It looks like your work on #152  is going to close this issue as well so I've unassigned myself for now. Happy to help out though if you'd like me to work on part of it.

**Comment by sparrowDom** [comment]
Hey @tomlinton thanks for the heads up. Yeah looks like this ticket should be resolved along with issue https://github.com/OriginProtocol/origin-dapp/issues/152 like you mention. And thanks will let you know if I need some help. 

I saw you cleared some stuff up and made better error reporting when doing https://github.com/OriginProtocol/origin-bridge/pull/113. Effort done there will help a lot with https://github.com/OriginProtocol/origin-dapp/issues/152.

**Comment by micahalcorn** [comment]
Done via #303 ✅
