### ISSUE TITLE
Better detection of environment in react for dev, staging, live, etc

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#30]
There are places where we use the page domain to detect if we are on the testnet installation. 

- https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/listings-grid.js#L23
This should probably be done via an environment variable. 

- Current url of the hidelist is hard-coded, but should also be an env var
https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/listings-grid.js#L27

- Maximum size of upload is hardcoded. Should be env var: https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/listing-create.js#L19

**Comment by ryana** [comment]
@wanderingstan I'm thinking about doing this:

```
--- a/src/components/listings-grid.js
+++ b/src/components/listings-grid.js
@@ -20,14 +20,7 @@ class ListingsGrid extends Component {
   componentWillMount() {
     // Get listings to hide if on demo
     const hideListPromise = new Promise((resolve, reject) => {
-      if (window.location.hostname !== "demo.originprotocol.com") {
-        resolve([])
-      } else {
-        resolve (
-          fetch('https://raw.githubusercontent.com/OriginProtocol/demo-dapp/hide_list/hidelist.json')
-          .then((response) => response.json())
-        )
-      }
+      resolve(process.env.HIDE_LIST)
     })
```

But while addressing the 1st item in your list, it renders your 2nd item moot. Is it important for the dev hide list to be a file hosted externally? Or can we just do that?

**Comment by wanderingstan** [comment]
The goal was for the hide list to easily editable when bad listings are found.  No so easy to ssh to the server, or commit to git. Putting it on github means we get to use their interface to update it quickly. I'm open to any other ideas here. 

Ah you're right about points 1 and 2: If I understand you, we can put the hidelist url in an env variable, and if it's empty, then we know not to use it.

**Comment by ryana** [comment]
Yeah ok the EDIT is what I was asking. (BTW for future reference: email notifications apparently don't get sent upon editing a comment).

So then... hmm. Could we do something where it always fetches from GitHub? e.g. `https://raw.githubusercontent.com/OriginProtocol/demo-dapp/hide_list/hidelist.dev.json` and `https://raw.githubusercontent.com/OriginProtocol/demo-dapp/hide_list/hidelist.prod.json`?

From one angle, that's no good since it forces people to have an internet connection to run the demo locally, but we're already forcing that since they need to access our IPFS gateway.

Lastly, I could just change

```
if (window.location.hostname !== "demo.originprotocol.com") {
```

to 

```
if (process.env.NODE_ENV !== "production") {

```

but that also feels meh to me.

So wacha think?

**Comment by ryana** [comment]
tagging @wanderingstan to trigger a notification on last comment.

**Comment by wanderingstan** [comment]
@ryana To me most natural is to put URL of the hidelist in an env variable. And if the var is not set, then that means nothing gets hidden. 

That way we can set it in our prod environment, and test it in our locals. But in the default case, nothing is hidden, and no extra web calls are made.

**Comment by ryana** [comment]
cool. i like it.

**Comment by wanderingstan** [comment]
Hidelist and env detection is pretty set now. 

Closing.
