### ISSUE TITLE
Arbitration: Integrate Existing Components

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#309]
Once https://github.com/OriginProtocol/origin-js/issues/278 is completed, the purchase-detail and purchase-progress components (at least) will need to be modified to handle the creation and resolution of disputes.

**Comment by wanderingstan** [comment]
Zeplin UI here: https://zpl.io/2GOw8zj

**Comment by micahalcorn** [comment]
Considering the first iteration of this to be done 😁
