### ISSUE TITLE
Request: Test DApp on Brave on a PC

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin-dapp#330]
We would love your help testing the DApp on a PC with the [Brave browser](https://brave.com).

Please report your findings below for the following:
- Log in to http://demo.orginprotocol.com
- Create an attestation
- Create a listing
- Purchase an item

Feel free to make PR to the [ReadMe test section](https://github.com/OriginProtocol/origin-dapp#browser--wallet-compatibility) with your results.

**Comment by davecraige** [comment]
cc @acal

**Comment by micahalcorn** [comment]
@acal should also make his membership in the GitHub organization public instead of private 😄 https://help.github.com/articles/publicizing-or-hiding-organization-membership/

**Comment by acal** [comment]
I had no idea it was set to private! Not sure where to change that @micahalcorn. So Brave on PC is operational. The one difference in functionality is that Metamask does not pop up when conducting a transaction. Instead there is just a numerical indicator that appears next to the Metamask extension icon on the browser toolbar. So unless you think to look for that you are left waiting for the metamask popup which will never come unless you click the toolbar icon. Not a bug but perhaps we can improve that aspect of the UI.

**Comment by LukaNarat** [comment]
Can reconfirm @acal's findings here. Didn't notice it was tested already. Should  README.md be updated @davecraige ?

just for reference:

Attestation: https://demo.originprotocol.com/#/users/0xDfCe568AA6BA3dbF98E9F05667Ff59c204851582

Listing Creation: https://demo.originprotocol.com/#/listing/0xa5655d90Ac0fC8B2551C1Db2a69a86F79ce5D3dB

Item Purchase: https://rinkeby.etherscan.io/tx/0xcc152e89e0578620422791e86d6600a49828122f7e5192a2c490d0c87ee863cb

**Comment by acal** [comment]
With latest release the other day of Origin-js and DApp it needs to be retested @LukaNarat . I did find yesterday that with Brave I could not create a listing or update my profile. Recommend this be reopened here or as a new issue.

**Comment by LukaNarat** [comment]
The above results are from today, PC+brave, worked fine.
(the modal not appearing from metamask is still present, as you described. Otherwise worked fine)

**Comment by davecraige** [comment]
Nice work on this @acal and @lukanarat. 😀 I can touch base with Stan and Micah soon about this.
