### ISSUE TITLE
Chinese language variants not supported, language naming convention

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#340]
Currently the DApp only has [one Chinese translation](https://github.com/OriginProtocol/origin-dapp/tree/develop/translations/languages/Chinese), while we need to support both Traditional (`zh-Hant`, used in Taiwan) and Simplified (`zh-Hans`, used in China mainland).

Observations:
- On crowdin, we have both traditional and simplied translations. ([link](https://crowdin.com/project/originprotocol/settings#translations))
- It looks like Crowdin PRs do include both chinese variants, as seen e.g. [here](https://github.com/OriginProtocol/origin-dapp/blob/2983e04704e68a767cd4fcaf25aac5c47a3919d9/translations/languages/Chinese%20Traditional/all-messages.json). 

Further recommendation:
- In our directory names and in code, we should always refer to languages by the locale code, e.g. `en`, or `zh-Hans`. This because eventually we will want support further locales, such as UK English (`en-gb`) or Austrian German (`de-at`). 
- Looks like crowdin is currently set to export using the English name of the language (`/translations/languages/%language%/%original_file_name%`), reccomend we instead use the locale code: `/translations/languages/%locale%/%original_file_name%`

**Comment by jordajm** [comment]
@wanderingstan @coleman415 it looks like I no longer have access to configure the github integration on crowdin - could one of you please take a look?

**Comment by wanderingstan** [comment]
There isn't much to configure there except to select which branch to use and to authorize Crowdin to Github. 
![image](https://user-images.githubusercontent.com/673455/43686548-136506ba-9885-11e8-9378-e4c98196acee.png)

Just guessing, might you be thinking of the settings for how files get merged? This is handled by double-clicking a folder/file here:
https://crowdin.com/project/originprotocol/settings#files
(There navigation is anything but clear!)

**Comment by micahalcorn** [comment]
Done via #348 ✅
