### ISSUE TITLE
Token: About Page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#363]
Build an About page explaining Origin Tokens.

See https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b602542f0e886e30b9ff4c7

**Comment by davecraige** [comment]
Happy to take a pass on copy when requested.

/ @aure

**Comment by mek32390** [comment]
@micahalcorn @matthewliu is there copy to add to this page?

**Comment by micahalcorn** [comment]
@mek32390 the token UIs are not quite ready, but thanks for getting this one started. 😬

**Comment by mek32390** [comment]
no problem, I kinda figured that. It's ready for copy and video.

**Comment by micahalcorn** [comment]
I'm going to consider this done and reserve copy work for a separate issue. ☑️
