### ISSUE TITLE
Messaging text not localized in popup

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#375]
Testing in German, the messaging popup shows English: "Unread Messages" and "View All"

![image](https://user-images.githubusercontent.com/673455/43931482-cb488544-9bfb-11e8-8149-84109d4183b4.png)

**Comment by micahalcorn** [comment]
Fixed in https://github.com/OriginProtocol/origin-dapp/pull/369 ✅
