### ISSUE TITLE
Various strings not translated

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#376]
Viewing DApp in German, http://localhost:3000/#/my-purchases shows in English. 

![image](https://user-images.githubusercontent.com/673455/43931559-3d1d5906-9bfc-11e8-8865-cc88cd5177d0.png)

Also 

![image](https://user-images.githubusercontent.com/673455/43931600-86257dd6-9bfc-11e8-82aa-e82b709cb8d5.png)

**Comment by micahalcorn** [comment]
All but the "Browse Listings" link appear to already be wrapped. The link is repaired by https://github.com/OriginProtocol/origin-dapp/pull/377.

**Comment by micahalcorn** [comment]
Considering this done via #377 ☑️
