### ISSUE TITLE
Messaging: Disable If Web3 Is Not Present

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#393]
Similar to the way that we handle the buy button in Safari, messaging features should be disabled if an ETH account cannot be detected.

**Comment by Natasha08** [comment]
@micahalcorn can you assign this to me?

**Comment by micahalcorn** [comment]
@Natasha08 done thx 🙏

**Comment by Natasha08** [comment]
@micahalcorn is this the solution you're referring to for Safari? ![image](https://user-images.githubusercontent.com/17957496/45569782-d6aca080-b81d-11e8-92de-c9df9fd67e90.png)

**Comment by micahalcorn** [comment]
Resolved by #506 ✅
