### ISSUE TITLE
Airbnb attestation fails without error if bridge server unavailable

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dapp#394]
Currenlty our demo evnironment [demo-dapp-testing](https://demo-dapp-testing.herokuapp.com/#/profile) does not have up to date bridge server deployed on [https://bridge.originprotocol.com/api](https://bridge.originprotocol.com/api). In this case the Airbnb attestation fails without error

**Comment by sparrowDom** [comment]
Pull Request for this issue: https://github.com/OriginProtocol/origin-dapp/pull/395

**Comment by sparrowDom** [comment]
@micahalcorn will someone also deploy the latest bridge-server code on https://bridge.originprotocol.com/api?

**Comment by micahalcorn** [comment]
Yeah, I don't think we've gotten that far yet. 😕
