### ISSUE TITLE
Add method for getting version of origin-js

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#399]
> **wanderingstanToday** at 10:56 AM
> :question: Is it possible to get the version of origin-js from the window.originTest object? Looks like there is a .version() method on the actual npm package, but I don't see a way to get to it from the var in the browser.  @DanielVF @micah  ?

> **DanielVFToday** at 10:57 AM
> Sec
> Nope - but that would be a great thing to add
>

**Comment by austinaryain** [comment]
It looks like this has been resolved and can be closed.

**Comment by micahalcorn** [comment]
Thx @austinaryain 👊
