### ISSUE TITLE
Re-create featured listings to enable localization

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#402]
Our current "Featured Listings" were created using an old (the first, in fact) version of our json-schema, which pre-dates localization.  Thus the section titles (e.g. "VACATION RENTALS") do not get translated. 

![image](https://user-images.githubusercontent.com/673455/44122652-1695aac4-9fe2-11e8-9cf7-eeb71ee0804e.png)

(To be technical, the old jsonschema had literal english, while we now use ids such as `schema.forSale.sportingGoods` instead of `Sporting Goods`)

The fix is
1. Re create these listings using the modern DApp
2. Update the DApp to feature these new listings.

**Comment by davecraige** [comment]
Happy to take a pass on recreating these listings.

**Comment by davecraige** [comment]
Ok, here are the listings recreated:
http://demo.originprotocol.com/#/listing/0x37e35851854C575CF411A5c12D4716305A3dc651
http://demo.originprotocol.com/#/listing/0xab18b45E8d0a96bBD9b160b8f5e07fA71D3Bb14a
http://demo.originprotocol.com/#/listing/0x3a57F3a93539b9742ea84CB5f6411b6338276FFc
http://demo.originprotocol.com/#/listing/0x838FbAC4246d1e0EC52777D7b011c49aaD7eD2c1

And a chicken one too 🐓
http://demo.originprotocol.com/#/listing/0x5a5f4C0F8A8DD3547AeEcE54ae7f15d75C7E7B48

A few user experience notes:
+ I wonder if other users will mix up the taxonomy a bit.  I accidentally clicked "For Sale" when I was supposed to list the real estate in "Housing."  I wonder if the term "Items for sale" might be clearer.

+ Speaking of taxonomy I believe there may be a duplicate when it comes to musical performances  _For sale >> Tickets_ and _Tickets >> Music_ seem to be the same general category.

+ Transactions feel really slow to complete.  I wonder if some sort of installation bar or something could make the experience a bit more palatable. Here is how Apple does it:

![apple-loading-bar-630x630](https://user-images.githubusercontent.com/2782676/44128551-d359bf38-a000-11e8-886f-27008199bca3.jpg)

**Comment by wanderingstan** [comment]
Thanks @davecraige !

Your additional points are all good, but we should keep this focussed on the issue at hand, "Re-create featured listings to enable localization". 

Can you create a separate issue(s) with your other concerns so they can be discussed and fixed on a case-by-case basis? 

We'll be closing out this issue as soon as we get your newly created listings featured, and I wouldn't want all your other thoughts lost.

**Comment by davecraige** [comment]
@wanderingstan sure!  

(Do you by chance have any suggestions on the proper way to name the new issue?  Something like "DApp Chrome Desktop user experience notes" Or something?  Would love any feedback you have on that.)

**Comment by wanderingstan** [comment]
We can close it... we can now close an important chapter in Origin history, and say goodbye to Ms. Swift, that '77 jeep thing, zinc housing, and our dreams of Hawaiian mansion living. 

![giphy](https://user-images.githubusercontent.com/673455/46055733-977a2b80-c10a-11e8-8f9b-2b072eec7203.gif)
