### ISSUE TITLE
Consider expanding description section / allowing resizing

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin-dapp#403]
Wondering if we should give users a bit more room to fill in long descriptions.  Example of a long listing that could use more space in the description section:

![screen shot 2018-08-14 at 5 31 56 pm](https://user-images.githubusercontent.com/2782676/44124254-7ef69d74-9fe9-11e8-8451-97129c56560c.png)

Also, any thought on maybe adding a resize handle to the bottom right like sites like Github and Wordpress have.  Might make it easier for users to select the size of the description box that they would prefer.
![text-box-drag](https://user-images.githubusercontent.com/2782676/44124278-a0e1ee02-9fe9-11e8-8dd4-14b2ed2e1820.jpeg)

Note: I chatted with @auregimon about this in Discord.  He seemed to agree as well.  _"That should be a textarea and yes, i like the resize thingy "_

**Comment by micahalcorn** [comment]
Note that this is probably not just a simple HTML change; it probably stems from our JSON schema. But it should be a simple fix nonetheless +/- a CSS property.

**Comment by jordajm** [comment]
@micahalcorn this can probably be closed b/c it's covered in https://github.com/OriginProtocol/origin-dapp/issues/432

**Comment by micahalcorn** [comment]
Now tracked by https://github.com/OriginProtocol/origin-dapp/issues/432 ☑️
