### ISSUE TITLE
Messaging Localization: Tom from MySpace only speaks English?

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#406]
![image](https://user-images.githubusercontent.com/673455/44152157-02c08340-a062-11e8-973a-f61b3f4dd4de.png)

The messaging "Welcome Message" is in English only. I don't think we want to imply that we can provide support in any language, but I think we can be more graceful about it. How about we get the standard welcome message translated, but then add an extra sentence saying something to the effect, "Unfortunately, we are only able to provide assistance in English at this time."* 

As this message is "faked", I believe it shouldn't be hard to run it through our regular localization functions.

<sup>*Or maybe English, French, Korean, German, Chinese, Slovenian, and Scottish, as those are the languages spoken by our team?? 😀</sup>

**Comment by wanderingstan** [comment]
Update: Looks like at least Japanese has the welcome message translated. 

![image](https://user-images.githubusercontent.com/673455/44152582-243469c8-a063-11e8-8c01-b199150ae56a.png)

So is this merely a case of missing translations? @coleman415 @jordajm ?

**Comment by micahalcorn** [comment]
This was a late addition so it may have come after the last round of machine translations.

**Comment by wanderingstan** [comment]
Confirmed, we have the message translated:
https://crowdin.com/translate/originprotocol/63/en-de#q=Welcome+to+the+Origin+Protocol

@jordajm Can you get latest translations merged into release branch (and stretch goal: update the translations/README.md with info about the language whitelist functionality you added yesterday)
