### ISSUE TITLE
Provide Listing Image Size Guidance

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin-dapp#410]
[micah] **Edit 9/24/2018**

In the future, [we will allow larger image uploads](https://github.com/OriginProtocol/origin-dapp/issues/489). Until then, we should provide more information to the user regarding their image(s) selection relative to the allowable limits. The user experience will be less frustrating if more information is available about the appropriate file size.

--------
It appears as though there is a limit on the number and size of images that you can upload.  Does anyone have more information on exactly what that limit currently is?

Here is the error message that I am seeing when I simply tried to recreate Stan's exact listings.  ( https://github.com/OriginProtocol/origin-dapp/issues/402 )
![screen shot 2018-08-14 at 5 41 06 pm](https://user-images.githubusercontent.com/2782676/44177487-6d653080-a0ab-11e8-8641-ad3e88aeee4b.png)

+ There seems to be a more stringent limit on images we can upload.  I tried to upload the same images for each listing when @wanderingstan requested but I kept getting the error message that the images were too big or too many.

+ Also any thoughts on possibly showing image sizes in MB and KB for simplicity sake.
![screen shot 2018-08-14 at 8 38 30 pm](https://user-images.githubusercontent.com/2782676/44128799-17a286a6-a002-11e8-938f-2446c6d22839.png)

**Comment by micahalcorn** [comment]
Relevant: https://github.com/OriginProtocol/origin-dapp/pull/217

**Comment by micahalcorn** [comment]
Editing this title and opening comment... 🛠

**Comment by wanderingstan** [comment]
...also relevant, going back to freakin _**January**_: https://github.com/OriginProtocol/origin-dapp/issues/44

What resizing tool are we using in #217? Something like [this js](https://stackoverflow.com/a/47398705/59913)?

**Comment by micahalcorn** [comment]
@wanderingstan I was just mentioning this to @franckc earlier today: a scaled back version of https://github.com/mosch/react-avatar-editor#readme

**Comment by davecraige** [comment]
@micahalcorn thanks for the update.  

_Note_: feel free to edit any of my issues, titles or comments anytime.  I appreciate your succinct and focused writing style. (And one thing I want to keep improving is how to write very clear issues going forward)

**Comment by micahalcorn** [comment]
Resolved by #586 with a fix to #489 on the way ✅
