### ISSUE TITLE
Force HTTPS Redirect With Environment Variable

### ISSUE THREAD

**Issue by jonhearty** [OriginProtocol/origin-dapp#417]
Tried to click the "Enable messaging" CTA but nothing happened when doing so. Turns out it's because I wasn't on https://demo.originprotocol.com, but just demo.originprotocol.com -- need to change the UI to make it clear what's happening and/or redirect to https://

<img width="1469" alt="screen shot 2018-08-17 at 4 09 29 pm" src="https://user-images.githubusercontent.com/3673242/44292216-33756500-a238-11e8-8558-872a8d640944.png">

**Comment by joshfraser** [comment]
Good catch @jonhearty.

We should always force the redirect to https.

**Comment by micahalcorn** [comment]
Done via https://github.com/OriginProtocol/origin-dapp/commit/5baaf790d8d46fb95347c2a171277f8519eada2b ✅
