### ISSUE TITLE
"Next Step" not localized

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#421]
The text **Next Step** is not localized on my-sales page.

https://demo.originprotocol.com/#/my-sales

![image](https://user-images.githubusercontent.com/673455/44414064-1c7d8e00-a52a-11e8-832a-01f7ade19b92.png)

![image](https://user-images.githubusercontent.com/673455/44413705-46828080-a529-11e8-9a0d-3b5011135c8c.png)

**Comment by jordajm** [comment]
Fixed by https://github.com/OriginProtocol/origin-dapp/pull/559
