### ISSUE TITLE
Token: Listing Creation Features

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#432]
The listing creation process now requires several updates.

**[Details](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b7538ac402bbf605c9afde5)**
- [x] description rendered as textarea
- [x] incremental photo UX
- [x] improved price field
- [x] currency conversion hint with explanation

**Comment by jordajm** [comment]
Completed by https://github.com/OriginProtocol/origin-dapp/pull/441
