### ISSUE TITLE
Token: Boost Listing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#434]
A step needs to be added to the listing creation process for optionally boosting the listing.

The component requires the following:

**No OGN**
- [x] [expandable alert](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b7baa2d3d5d132236e085ec)

**With OGN**
- [x] [explanation tooltip](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b7538af34bc6308a88e5406)
- [x] [adjustable slider](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b7538ade2372d21ec0ff291)
- [x] [dynamic labels and values](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b7538adc6e1eda75f4976e4)
- [x] [insufficient balance alert](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b7538afba91c80514c42804)

**Comment by jordajm** [comment]
Done by https://github.com/OriginProtocol/origin-dapp/pull/450
