### ISSUE TITLE
Fix hidelist in `master`

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-dapp#443]
In the current `master`, our hidelist functionality is a bit awkward. Hidden listings are not accounted for in the pagination, thus there is whitespace in place of hidden listings in the grid. We should filter out hidden listings in the list *before* pagination to avoid this issue.

**Comment by micahalcorn** [comment]
Resolve by https://github.com/OriginProtocol/origin-dapp/pull/438 ✅
