### ISSUE TITLE
Rich Message Content

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#477]
#476 provides functionality for users to upload a single image file as message content and for it to render in an existing conversation thread - the bare minimum requirement to support supplying photographic evidence to arbitrators once a dispute has been initiated. This issue tracks additional functionality, UX improvements, and other considerations.

1. A conversation must already exist between two users in order to upload an image. It may be appropriate to start a conversation with an image from elsewhere in the DApp or allow for content to be included with the initiation of a dispute.

2. Only a string OR a file can be sent as a message. If a user types a value into the `textarea` and then clicks the image icon, the text value will be lost. A better experience would be similar to Discord or iPhone where the image and text can be sent as a combined package.

3. Only a single file can be sent in one message. Supporting multiple files would seem to be reasonable, but there are UX and native browser complications for users to intuitively add more than one image.

4. We current send the image as a data uri in the form of a really long string. This is slow and probably not optimal for many reasons.

5. As a consequence of 4, there is a delay between submitting the form and the image being uploaded. The button should be disabled during this time and/or there should be some kind of "processing" indicator if only to prevent multiple submissions.

6. As an alternative to 4, we should probably prescribe a standard structure for message objects. We currently only expect (and validate) a `created` timestamp and a `content` string. If we're going to use data uris and want to support multiple files, we should use designate something like a `data` array and make `content` optional.

7. There may be a better or more efficient way to store the images and then reference them from the message object instead of storing so much data in OrbitDB. I'm not sure how we would do this and maintain security/privacy. At least this way, the image data is encrypted. As an alternative, we could leave the image security up to the user and settle on encrypting the reference to the image location and thereby obscuring its connection to the message/transaction/user/etc.

8. We don't currently provide a way to cancel the image once it is selected with the file input. The native UX for changing the file is to click on the icon again, but users will have to refresh the browser (or change the route or selected conversation) if they want to return to the text option.

9. We don't currently validate the file type. If some other message content is sent containing a data uri, we provide a message stating that we are unable to render it.

There are probably some easy improvements to be made here. I just wanted to jot down some thoughts before I forget them. cc @wanderingstan @crazybuster

**Comment by crazybuster** [comment]
Couple of points...
1) Storing image data is good, because it allows for auditing without the possibility of the image disappearing. We should probably disallow linked images.

2) Should probably have enforcement of the size of messages on both the client and the persistence server side so that users can't be bombed by large data blobs.

2) Should probably have a separate field the schema for linked images/files because inferring the images might not always be correct, and allow for better error handling and filter(like enforcing that this is really an image)

**Comment by micahalcorn** [comment]
Resolved by #476 ✅
