### ISSUE TITLE
Implement showing reviews on profile page

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dapp#482]
The code on the DApp side for fetching and showing reviews on the user profile page hasn't been implemented yet: https://github.com/OriginProtocol/origin-dapp/blob/master/src/pages/user/User.js#L30

**Comment by micahalcorn** [comment]
Seems to have been lost [awhile ago](https://github.com/OriginProtocol/origin-dapp/commit/95931b92fd9ca6a83cc4871e38806cfdaf3f43ac#diff-851b5ff79682a04c9b053d34a5cba5ddR28) 😕

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin-dapp/pull/523 ✅
