### ISSUE TITLE
Messages not displaying in chronological order

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin-dapp#490]
It appears as though some individual messages get moved around and are not being displayed chronologically. Note the timestamps for this conversation with Kay (Micah):

<img width="877" alt="screen shot 2018-09-11 at 2 21 20 pm" src="https://user-images.githubusercontent.com/2782676/45449828-4434c180-b6a4-11e8-9bc0-c671f4a4f3bd.png">

Here is another example from a conversation with Luka.  Note how the messages shift.

_Before_
<img width="740" alt="screen shot 2018-08-24 at 3 35 07 pm" src="https://user-images.githubusercontent.com/2782676/44609059-70e76e80-a7b3-11e8-8c05-61599b592d8e.png"> 
 
_After_
<img width="749" alt="screen shot 2018-08-24 at 3 35 35 pm" src="https://user-images.githubusercontent.com/2782676/44609060-70e76e80-a7b3-11e8-902b-aab911870c56.png">

**Comment by davecraige** [comment]
Thanks @micahalcorn 🙏

**Comment by davecraige** [comment]
One additional note, I believe messages should be ordered chronologically with the most recent person you spoke to at the top.  This is the heuristic used by other messaging apps such as Facebook and Twitter.

<img width="286" alt="screen shot 2018-09-19 at 3 28 40 pm" src="https://user-images.githubusercontent.com/2782676/45782673-de56b580-bc20-11e8-9f46-37500e266674.png">
(note: I just sent a message to )

**Comment by micahalcorn** [comment]
Yes 👉 https://github.com/OriginProtocol/origin-dapp/issues/383

**Comment by davecraige** [comment]
Oh nice.  You are already on top of that.  Good stuff!

**Comment by micahalcorn** [comment]
Let me know if this isn't fixed by https://github.com/OriginProtocol/origin-dapp/pull/672. 🤞

**Comment by davecraige** [comment]
Nice, working really well for me now.  Thanks Micah 😀.
