### ISSUE TITLE
Facebook OAuth failing

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-dapp#494]
Facebook attestations in the DApp are currently failing as reported in #328.

The app is currently doing the OAuth handshake using client id=179007166076828 (the one @nick initially setup then deleted) instead of 124441901753956 as defined in EnvKey. @tomlinton any idea why this variable isn't getting passed through correctly?

**Comment by tomlinton** [comment]
In the Heroku setup a bunch of environment variables (Settings/Reveal Config Vars in the Heroku dashboard) are defined in addition to EnvKey. The environment variables are [processed after EnvKey](https://github.com/OriginProtocol/origin-bridge/blob/016edc1495f5301bb3a0541f1e2afea19fc4c107/config/settings.py#L64-L65) so they'd overwrite them (in the new production setup I'm building we are strictly EnvKey for the bridge settings). I nuked the Facebook settings in Heroku and restarted the bridge dyno so 124441901753956 is now passed correctly.

Now we have this error from Facebook:

`Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.`

@joshfraser do you have access to the Facebook app settings to update that?

**Comment by joshfraser** [comment]
Aha! Updated and seems to be working again. Thanks @tomlinton!
