### ISSUE TITLE
Get started selling origin modal issues

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dapp#497]
The modal dialog saying `Get started selling origin` prevents user input in the following cases: 
- as long as dialog is shown clicking on `general search input` does not work. 
- if user opens a webpage and clicks on `notification bell icon` -> `view all button` -> `back` using browser navigation. The modal blocks clicking anywhere on the page and shows a semi transparent white backgorund (see image below)
<img width="1389" alt="screenshot 2018-09-13 15 07 42" src="https://user-images.githubusercontent.com/579910/45490784-55470680-b768-11e8-98b6-b88ed1c368a4.png">

**Comment by micahalcorn** [comment]
Resolved by #502 ✅
