### ISSUE TITLE
Listing Creation: Unfortunate Validation Failure

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#513]
Listing creation seems to fail validation if the currency conversion cannot be calculated. This can be reproduced by running a local blockchain offline. When attempting to create a listing, it produces two validation errors in different parts of the form, neither of which are very helpful.

<img width="1440" alt="screen shot 2018-09-17 at 7 20 21 pm" src="https://user-images.githubusercontent.com/273937/45660722-1807af00-baaf-11e8-88cc-f169d5242ac4.png">

**Comment by jordajm** [comment]
Fixed by https://github.com/OriginProtocol/origin-dapp/pull/522
