### ISSUE TITLE
Fulfillment Checklist

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#530]
When a seller accepts an offer, we will display [a checklist](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5b9fd84cb410852d3e622cc3) to suggest what she should probably do to fulfill her obligations to the buyer. This should probably be handled in the schemas similarly to the way we handle listing type examples in the creation form. However, this won't need to be rendered as a form.

- [ ] build component
- [ ] populate via schema

**Comment by jordajm** [comment]
@micahalcorn is there a to-do list for each listing type that exists somewhere? Or should I just kinda make it up as I go along (if I promise not to talk about chickens)?

**Comment by micahalcorn** [comment]
Just throw some distinct placeholders in there for now. Don't spend too much time on the copy.

**Comment by jordajm** [comment]
Done by https://github.com/OriginProtocol/origin-dapp/pull/543
