### ISSUE TITLE
Swap out "Kay from Origin" with a generic "Origin Support" name and profile picture

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-dapp#531]
While I was the original person to propose having our own version of Tom from Myspace, in practice I think it's a bit weird to have multiple people on our team impersonating Kay. We should update that account before mainnet.

**Comment by micahalcorn** [comment]
Updated ✅ Maybe at some point it's worth revisiting with a fake persona.

![cat-support](https://user-images.githubusercontent.com/273937/45786022-6938af80-bc23-11e8-88ac-8c46b967d8a9.gif)
