### ISSUE TITLE
Error publishing profile

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dapp#547]
When you change your profile information and/or attestations and try to publish them the following error with no metamask confirmation is thrown: 
```
Returned values aren't valid, did it run Out of Gas?
    at s.decodeParameters (app.7f507472.js:6371)
    at s.decodeLog (app.7f507472.js:6371)
    at Object.d._decodeEventABI (app.7f507472.js:6377)
    at app.7f507472.js:1345
    at Array.map (<anonymous>)
    at c.formatOutput (app.7f507472.js:1345)
    at a (app.7f507472.js:1345)
    at app.7f507472.js:15831
    at inpage.js:1
    at inpage.js:1
```

(this happens on staging environment on Rinkeby)

**Comment by franckc** [comment]
@nick @tyleryasaka Any idea what the issue could be ?

Also CCing @micahalcorn

**Comment by tyleryasaka** [comment]
web3's `estimateGas` method doesn't return sufficient estimates for attestations, so we are currently hard coding the gas amounts. Perhaps we just need to increase these amounts a bit.

https://github.com/OriginProtocol/origin-js/blob/master/src/contractInterface/users/v00_adapter.js#L130

**Comment by franckc** [comment]
@tyleryasaka: @sparrowDom is done for the day since it is already late in Europe... Would you be ok working on a fix this afternoon ? thanks in advance.

**Comment by tyleryasaka** [comment]
Ok I don't think it's the problem I suggested in the previous comment.

Confirmed the error is coming from this line: https://github.com/OriginProtocol/origin-js/blob/staging/src/contractInterface/users/v00_adapter.js#L159

**Comment by tyleryasaka** [comment]
Reading through the issue @sparrowDom linked to, I'm not sure what we can do about this. We could roll back web3 to beta.34 but that would introduce breaking changes.

This is not a bug on our end. This is what happens when we try to use beta software in production. 😬

**Comment by tyleryasaka** [comment]
The other possibility is that we can change our event signature to not have all indexed parameters. See https://github.com/ethereum/web3.js/issues/1916#issuecomment-422805852

**Comment by franckc** [comment]
This fix should help with this issue: https://github.com/OriginProtocol/origin-js/pull/530
