### ISSUE TITLE
Email Verification code expired

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dapp#548]
On staging environment the email attestation throws `Verification code has expired` when entering the code sent via email. 

Code that checks this: https://github.com/OriginProtocol/origin-bridge/blob/b231dbcd76898c25c848f2f7a71da3881054b22a/logic/attestation_service.py#L238-L239

Could it be that the server's local time is off?

**Comment by franckc** [comment]
@tomlinton any idea on this one ?

**Comment by franckc** [comment]
From Tom: "It's because we have multiple bridge servers and no sticky sessions and the verification codes are stored in sessions"

**Comment by tomlinton** [comment]
Fixed in https://github.com/OriginProtocol/origin-box/pull/74.

**Comment by sparrowDom** [comment]
Works for me on staging 👍
