### ISSUE TITLE
Arbitration: Wire up "enable messaging" button

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/origin-dapp#560]
When a user clicks "report a problem", if they haven't enabled messaging previously, they are presented with a modal that contains a button that says "enable messaging".

Clicking this button causes an alert that says "to do".

This button needs to be wired up to actually enable messaging.

<img width="493" alt="screenshot 2018-09-23 00 21 09" src="https://user-images.githubusercontent.com/5402813/45924817-a1135180-bec6-11e8-910c-539481d3fdd9.png">

CC @micahalcorn - couldn't find an issue for this but LMK is there is one already somewhere

**Comment by micahalcorn** [comment]
Resolved by #562 ✅
