### ISSUE TITLE
🐃 "From" and "To" fields on purchase transaction history show wrong addresses

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dapp#564]
The columns labeled "From" and "To" on the purchase transaction history show the "buyer" and "seller" in the actual data rows. However the offer transactions are initiated by different parties and so these addresses often have the wrong "from" and "to" label. 

I'm also not sure we event need a "To" column at all - it's sufficient to know who initiated each transaction.

![image](https://user-images.githubusercontent.com/837/45961805-68ba6300-bfed-11e8-8bf4-b90429638fb7.png)

**Comment by DanielVF** [comment]
I'll change this one over to showing just the from, and using the correct values. @micahalcorn could take it from there, if there's more.

**Comment by micahalcorn** [comment]
@DanielVF yeah, there is also a "to" concept in [the blockchain transaction confirmations](https://github.com/OriginProtocol/origin-dapp/blob/master/src/components/transaction.js#L60-L91), which isn't always intuitive or particularly necessary.
