### ISSUE TITLE
Notification of profile update not appearing

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin-dapp#619]
When I publish my profile, I am not seeing any properly named notification to show me that it is being updated even though the modal said I would be seeing it.

Screenshot of my notifications:
![screen shot 2018-09-28 at 1 35 43 pm](https://user-images.githubusercontent.com/2782676/46229649-8e17db80-c323-11e8-8917-a525665559f7.png)

**Comment by franckc** [comment]
@sparrowDom Could you take a look ?

**Comment by sparrowDom** [comment]
Yup on it :)

**Comment by sparrowDom** [comment]
Fix for this located here: https://github.com/OriginProtocol/origin-dapp/pull/625
