### ISSUE TITLE
Should the user see 1 unread message on first login

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin-dapp#620]
To encourage more people to click the "enable messaging" should we show the user one unread message? (The one coming directly from Origin's welcoming account).  Currently it shows 0.

Current screenshot:
![screen shot 2018-09-28 at 1 39 52 pm](https://user-images.githubusercontent.com/2782676/46229843-34fc7780-c324-11e8-8ff8-72e87b3179d5.png)

/ @auregimon

**Comment by joshfraser** [comment]
Yeah, my original idea for the welcome message is that it would show up as 1 unread message as a motivation to get people to enable it to see what it says.

**Comment by micahalcorn** [comment]
Repaired by https://github.com/OriginProtocol/origin-js/pull/578 ✅
