### ISSUE TITLE
Double error message on new listing creation with short description

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin-dapp#623]
When a user makes a new listing with a short description there are a few errors:

- Error message shows up twice
- Copy could be fixed a bit.  Could say " Descriptions must be at least 10 characters or more.  Please write a longer description." 

Screenshot: 
![screen shot 2018-09-28 at 3 01 34 pm](https://user-images.githubusercontent.com/2782676/46233339-6d558300-c32f-11e8-8b2b-0f78ba6ae387.png)

**Comment by micahalcorn** [comment]
@jordajm we shouldn't have the summary at the top summarizing all invalid fields.

**Comment by jordajm** [comment]
Resolved by https://github.com/OriginProtocol/origin-dapp/pull/641

**Comment by davecraige** [comment]
Thanks @jordajm!
