### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#63]
We can't be English/America-only. Let's get this DApp global! 

Overall plan is: 

Step 1: Choose localization library. Default choice for React would seem to be: [react-localization](https://github.com/stefalda/react-localization)

Step 2: Break apart current english strings and replace with appropriate l10n calls.

Step 3: Get translations for different languages. 

If you have an opinion on 1, or want to do some research, that'd be very useful. Step 2 will be the bulk of this issue. 

Sub-tasks created:

- [x] https://github.com/OriginProtocol/demo-dapp/issues/245
- [x] https://github.com/OriginProtocol/demo-dapp/issues/246
- [x] https://github.com/OriginProtocol/demo-dapp/issues/247
- ~https://github.com/OriginProtocol/demo-dapp/issues/248~
- [x] https://github.com/OriginProtocol/demo-dapp/issues/249
- [x] https://github.com/OriginProtocol/demo-dapp/issues/255
- [ ] https://github.com/OriginProtocol/demo-dapp/issues/263

**Comment by micahalcorn** [comment]
@wanderingstan do you want to link us here to the implementation(s) that you saw for us to reference?

**Comment by wanderingstan** [comment]
John J and I had discord convo on this, with me forgetting g we already had an open issue. 

His comment there: 
> cool - I'll look at swarm's stuff but I think this is the winner in terms of react i18n stuff:
> https://www.npmjs.com/package/react-intl

**Comment by jordajm** [comment]
`react-i18next` looks cool too though - worth checkout out - and @wanderingstan found this for translating between the json files it uses and `.po/.pot` files of `gettext`
https://www.npmjs.com/package/react-intl-po

**Comment by wanderingstan** [comment]
For reference: Here is our translation files & workflow or the website: 
https://github.com/OriginProtocol/company-website/tree/master/translations

**Comment by jordajm** [comment]
WIP PR:
https://github.com/OriginProtocol/demo-dapp/pull/238

**Comment by micahalcorn** [comment]
Considered done with https://github.com/OriginProtocol/origin-dapp/issues/263 split into sub-tasks ✅
