### ISSUE TITLE
If Metamask not installed, browsing to dapp.originprotocol.com redirects to staging

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dapp#640]
If I go to https://dapp.originprotocol.com but I don't have metamask installed, I get redirected to https://demo.staging.originprotocol.com/#/

Is that what we want ? I would think we want to show a message prompting the user to install metamask ?

**Comment by franckc** [comment]
CC @micahalcorn

**Comment by micahalcorn** [comment]
@franckc probably need to set `PROVIDER_URL` env var to not have a Rinkeby subdomain on the https://dapp.originprotocol.com/? 🤔

**Comment by franckc** [comment]
Wow. Great catch @micahalcorn !
Indeed, checking https://dapp.originprotocol.com/#/dapp-info shows:
`PROVIDER_URL=https://rinkeby.infura.io/emIXjs9eDuy57IlTYsIP`

Let me send a PR to fix the prod deployment... Thanks !

**Comment by franckc** [comment]
PR here: https://github.com/OriginProtocol/origin-box/pull/98
