### ISSUE TITLE
Analytics Event Tracking

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#642]
We need to track a ton of click events. I haven't had a chance yet to think of all of them, but the top priorities would be steps in user journeys such as seller onboarding, listing creation, identity profile/attestations, etc. Does anyone have experience with [react-ga](https://github.com/react-ga/react-ga) or know of a way that we can bootstrap the over-collection of valuable data and filter it out later?

**Comment by jordajm** [comment]
Resolved by https://github.com/OriginProtocol/origin-dapp/pull/657 and https://github.com/OriginProtocol/origin-dapp/pull/662
