### ISSUE TITLE
Basic support for featuring and hiding listings

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dapp#643]
For the V1 launch, we need a primitive way to:
- Feature listings on the browse page. Those listings should have a badge and show up at the top of the page (it's ok if it breaks pagination, e.g. if a larger than page size total number of listings are displayed on the first page due to featured listings being added on top).
 - Hide listings on browse and search page. This is to remove potentially offensive listings.
This could be as simple as the DApp fetching the listingIds to feature/hide from gist or a github file (see for example [prior implementation](https://github.com/OriginProtocol/origin-dapp/blob/master/src/actions/Listing.js#L42))

Post V1, as part of fetching listings for the browse page via back-end rather than web3, we'll implement a more robust hiding/featuring solution in the backend.

**Pull Request for this issue:**
- https://github.com/OriginProtocol/origin-dapp/pull/645
- https://github.com/OriginProtocol/origin-dapp/pull/654

**Comment by franckc** [comment]
CC @micahalcorn @matthewliu

**Comment by sparrowDom** [comment]
Solved via: 
- https://github.com/OriginProtocol/origin-dapp/pull/645
- https://github.com/OriginProtocol/origin-dapp/pull/654

**Comment by franckc** [comment]
Nice work @sparrowDom !
