### ISSUE TITLE
Profile UX Improvements

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#644]
- [ ] 1️⃣

The attestations naturally result in a "success" modal:

![verified](https://user-images.githubusercontent.com/273937/46273686-671bfe00-c50b-11e8-8094-9f3040f000ed.png)

When adding profile information - names, photo, description - there is provisional success modal encouraging the user to publish the changes. This should be added.

- [ ] 2️⃣ 

The unload modal currently only renders if the user tries to leave or load a new page. It should also render before allowing a route change if there are unpublished changes. Use the [`prompt` component](https://github.com/OriginProtocol/origin-dapp/blob/master/src/components/listing-create.js#L829-L832) for this.

**Comment by franckc** [comment]
@micahalcorn Is that truly a p0 that must be fixed before release ?

**Comment by micahalcorn** [comment]
It came out of the war room sessions. I don't know how to decide which of 100+ things are or are not p0. My plan is to just do as many as possible. 😓

**Comment by matthewliu** [comment]
P1 it

**Comment by micahalcorn** [comment]
Resolved by #702 ✅
