### ISSUE TITLE
String not translated "Contact Seller"

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin-dapp#720]
I believe the "Contact Seller" string is not properly translated 

Screenshot:

![screen shot 2018-10-10 at 9 32 26 pm](https://user-images.githubusercontent.com/2782676/46779329-874e7880-ccd4-11e8-972a-8893a95b9e75.png)

/ @mek32390

**Comment by davecraige** [comment]
Also quick note: I don't believe categories are either.  But not sure if that is beyond the current scope at this time

[Uploading Screen Shot 2018-10-10 at 9.34.33 PM.png…]()

**Comment by micahalcorn** [comment]
[Waiting on another round of machine translations](https://github.com/OriginProtocol/origin-dapp/blob/master/src/components/user-card.js#L162-L165) and https://github.com/OriginProtocol/origin-dapp/issues/678 😐

**Comment by davecraige** [comment]
Ok great, thank you 🙏
